---
title: "Changed to Initial Conditions NetCDF file"
author: "Gorton, Bec (Environment, Hobart)"
---

At this stage you will need to hand edit your initial conditions file. Remember ncgen/ncdump are the way to do this.

You will need to add an additional dimension at the top of the file:

dimensions:  
 t = UNLIMITED ; // (1 currently)  
 b = 11 ;  
 z = 7 ;  
 icenz = 2;

This is the max number of ice layers in your model.

Then for each ice group you will need to add a variable like the following:

double Ice_Diatom_N(t, b, icenz) ;

Ice_Diatom_N:bmtype = "icetracer" ;  
 Ice_Diatom_N:units = "mg N m-3" ;  
 Ice_Diatom_N:long_name = "Ice_Diatom Nitrogen" ;  
 Ice_Diatom_N:sumtype = 0 ;  
 Ice_Diatom_N:dtype = 0 ;  
 Ice_Diatom_N:inwc = 0 ;  
 Ice_Diatom_N:insed = 0 ;  
 Ice_Diatom_N:dissol = 0 ;  
 Ice_Diatom_N:decay = 0. ;  
 Ice_Diatom_N:partic = 1 ;  
 Ice_Diatom_N:passive = 1 ;  
 Ice_Diatom_N:svel = -2.893e-06 ;  
 Ice_Diatom_N:xvel = 0. ;  
 Ice_Diatom_N:psize = 1.e-05 ;  
 Ice_Diatom_N:b_dens = 1000000000. ;  
 Ice_Diatom_N:i_conc = 200000000. ;  
 Ice_Diatom_N:f_conc = 200000000. ;  
 Ice_Diatom_N:_FillValue = 0.001 ;  
 Ice_Diatom_N:inice = 1;

See the example files for more information.
