---
title: "Differences in Windows and Linux"
author: "Gorton, Bec (Environment, Hobart)"
---

There are some differences between output files for model when run under linux and windows.

From what i can tell the model parameters are loaded correctly. There are some very small (1e-14) differences in the loaded values.

But the differences just keep compounding the longer a model is being run. I'm going to have to track down what is causing these differences and work out how they can be mininised.

There are many differences in complier options. These are found by running the following small test case:[hello.c](#)

| Compiler | Notes | Calculation Accuracy | Storage Accuracy |
| --- | --- | --- | --- |
| Visual Studio | Improve Consistancy off and on | 16 | 16 |
| gcc 3.4.4 cygwin | No Optimisation | 20 | 16 |
| gcc 3.4.4 cygwin | O | 20 | 20 |
| gcc 3.4.4 cygwin | O2 | 20 | 20 |
| gcc 3.4.4 cygwin | O3 | 20 | 20 |
| gcc 4.1.3 Ubuntu | No Opt | 20 | 16 |
| gcc 4.1.3 Ubuntu | O | 16 | 20 |
| gcc 4.1.3 Ubuntu | O2 | 16 | 20 |
| gcc 4.1.3 Ubuntu | O3 | 16 | 20 |
| gcc 4.1.3 Ubuntu | -ffloat-store | 16 | 16 |
| gcc 3.4.6 Ubuntu | No Opt | 20 | 16 |
| gcc 3.4.6 Ubuntu | O | 20 | 16 |
| gcc 3.4.6 Ubuntu | O3 | 20 | 20 |
| gcc 4.1 Ubuntu | No Opt | 20 | 16 |
| gcc 4.1 Ubuntu | O | 16 | 20 |
| gcc 4.1 Ubuntu | O | 16 | 20 |
| gcc 4.1 Ubuntu | O3 | 16 | 20 |
| gcc 4.2 Ubuntu | No Opt | 20 | 16 |
| gcc 4.2 Ubuntu | O | 20 | 16 |
| gcc 4.2 Ubuntu | O2 | 16 | 20 |
| gcc 4.2 Ubuntu | O3 | 16 | 20 |

## Interesting Links

<http://www.coyotegulch.com/reviews/linux_compilers/>
