---
title: "Existing Atlantis Bowen Capacity"
author: "Gorton, Bec (Environment, Hobart)"
---

## Linux Bowen Virtual Machines:

oa-22-mel.it.csiro.au

oa-16-mel.it.csiro.au

## Bowen Storage:

Storage attached to oa-22-mel:

|  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- |
| Storage type | Description | Example Label |  | **Maximum storage quota** | Data protection |
| Work |  | **/input** | **Windows (CIFS) access from local Windows workstations:**  [\\osm-09-mel.it.csiro.au\OSM_MEL_OA_ALANTIS_input](file:///osm-09-mel.it.csiro.au/OSM_MEL_OA_ALANTIS_input)  **Linux (NFS) access only available from [OA-22-MEL.it.csiro.au](http://oa-22-mel.it.csiro.au/)**  /OSM/MEL/OA_ALANTIS/input | **1 TB** | Yes, data protected.    The Work category is for data sets that are currently being operated on. It is anticipated that data stored in a work area can be reproduced from Reference or Source data. |
| Work |  | **/output** | **Windows (CIFS) access from local Windows workstations:**  [\\osm-09-mel.it.csiro.au\OSM_MEL_OA_ALANTIS_output](file:///osm-09-mel.it.csiro.au/OSM_MEL_OA_ALANTIS_output)  **Linux (NFS) access only available from [OA-22-MEL.it.csiro.au](http://oa-22-mel.it.csiro.au/)**  /OSM/MEL/OA_ALANTIS/output | **1 TB** | Yes, data protected.    The Work category is for data sets that are currently being operated on. It is anticipated that data stored in a work area can be reproduced from Reference or Source data. |
| Work |  | **/archive** | **Windows (CIFS) access from local Windows workstations:**  [\\osm-09-mel.it.csiro.au\OSM_MEL_OA_ALANTIS_input](file:///osm-09-mel.it.csiro.au/OSM_MEL_OA_ALANTIS_input)  **Linux (NFS) access only available from [OA-22-MEL.it.csiro.au](http://oa-22-mel.it.csiro.au/)**  /OSM/MEL/OA_ALANTIS/archive | **2 TB** | Yes, data protected.    The Work category is for data sets that are currently being operated on. It is anticipated that data stored in a work area can be reproduced from Reference or Source data. |

Security Groups associated with this virtual machine and storage.

|  |  |  |
| --- | --- | --- |
| *Group* | *Role* | *Members* |
| ACL_STACC_OA-ALANTIS_ADM | Admin group – ability to add/remove users from other groups.  Also grants sudo access on compute node | Gorton, Bec (O&A, Hobart) Fuller, Mike (O&A, Hobart) |
| ACL_STACC_OA-ALANTIS_RW | Read/Write access to dataset | Gorton, Bec (O&A, Hobart) Fuller, Mike (O&A, Hobart) Fulton, Beth (O&A, Hobart) Pethybridge, Heidi (O&A, Hobart) Porobic Garate, Javier (O&A, Hobart) |
| ACL_STACC_OA-ALANTIS_RO | Read Only access to dataset |  |
| ACL_STACC_OA-ALANTIS_CON | Console – remote access to existing Bowen Research Cloud compute appliance. | Gorton, Bec (O&A, Hobart) Fuller, Mike (O&A, Hobart) Fulton, Beth (O&A, Hobart) Pethybridge, Heidi (O&A, Hobart) Porobic Garate, Javier (O&A, Hobart) |

---

|  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- |
| Storage type | Description | Example Label |  | **Maximum storage quota** | Data protection |
| Work |  | **/source** | **Windows (CIFS) access from local Windows workstations:**  [\\OSM-06-MEL.it.csiro.au\OSM_MEL_OA_GLADSTONE_MR_source](file:///OSM-06-MEL.it.csiro.au/OSM_MEL_OA_GLADSTONE_MR_source)  **Linux (NFS) access only available from [OA-16-MEL.it.csiro.au](http://oa-22-mel.it.csiro.au/)**   /OSM/MEL/OA_GLADSTONE_MR/source | **2 TB** | Yes, data protected.    The Work category is for data sets that are currently being operated on. It is anticipated that data stored in a work area can be reproduced from Reference or Source data. |
| Work |  | **/work** | **Windows (CIFS) access from local Windows workstations:**  [\\OSM-06-MEL.it.csiro.au\OSM_MEL_OA_GLADSTONE_MR_work](file:///OSM-06-MEL.it.csiro.au/OSM_MEL_OA_GLADSTONE_MR_work)[t](file:///osm-09-mel.it.csiro.au/OSM_MEL_OA_ALANTIS_output)  **Linux (NFS) access only available from [OA-16-MEL.it.csiro.au](http://oa-22-mel.it.csiro.au/)**   /OSM/MEL/OA_GLADSTONE_MR/work | **1 TB** | Yes, data protected.    The Work category is for data sets that are currently being operated on. It is anticipated that data stored in a work area can be reproduced from Reference or Source data. |

Security Groups associated with this virtual machine and storage.

|  |  |  |
| --- | --- | --- |
| *Group* | *Role* | *Members* |
| ACL_STACC_OA_GLADSTONE-MR_ADM | Admin group – ability to add/remove users from other groups | Linda Thomas tho756 and Beth fulton ful083, Bec Gorton  gor171 and Mark Baird  bai155 |
| ACL_STACC_OA_GLADSTONE-MR_RW | Read/Write access to dataset | Linda Thomas tho756, Bec Gorton gor171, Hector Lozano-Montes loz003, Trevor Hutton hut129, Beth fulton ful083, Mark Baird bai155, Nugzar Margvelashvili mar644 and Scott Condie con198 |
| ACL_STACC_OA_GLADSTONE-MR_RO | Read Only access to dataset | None |
| ACL_STACC_OA_GLADSTONE-MR_CON | Console – remote access to OSM | None |
