---
title: "Ice Forcing files"
author: "Gorton, Bec (Environment, Hobart)"
---

Similar to the temperature and salinity files you can provide an Ice forcing file. As previously discussed you specify the number of ice classes in the physics prm file. For each box on your model you need to provide information on the each ice class assuming 0.0 means that iceclass not present and value 0.0 is habitat presence and quality scalar.

You also need to provide the total depth of the ice in each box.

Assuming that there are 4 ice classes the file structure will be:

netcdf SETAS_VMPAIceSmall {  
dimensions:  
 t = UNLIMITED ; // (1 currently)  
 b = 11 ;  
variables:  
 double Ice_Class1(t, b) ;  
 Ice_Class1:_FillValue = 0.25 ;  
 double Ice_Class2(t, b) ;  
 Ice_Class2:_FillValue = 0.25 ;  
 double Ice_Class3(t, b) ;  
 Ice_Class3:_FillValue = 0.25 ;  
 double Ice_Class4(t, b) ;  
 Ice_Class4:_FillValue = 0.25 ;  
 double t(t) ;  
 t:units = "seconds since 1970-01-01 00:00:00 +10" ;  
 t:dt = 43200. ;  
 double total_depth(t, b) ;  
 total_depth:_FillValue = 0. ;

// global attributes:  
 :title = "trivial" ;  
 :geometry = "VMPA_setas.bgm" ;  
 :parameters = "" ;  
 :history = "Wed Aug 6 17:09:40 2014: ncks -d t,0,0 [SETAS_VMPAIce.nc](http://SETAS_VMPAIce.nc) [SETAS_VMPAIceSmall.nc](http://SETAS_VMPAIceSmall.nc)" ;  
 :NCO = "4.0.8" ;

A very small sample file is attached. - [SETAS_VMPAIce_14Jan2016.nc](attachments/243663521.nc)
