---
title: "Initial Conditions Errors"
author: "Gorton, Bec (Environment, Hobart)"
---

**Error message:**

ncattget: ncid 65536: NetCDF: Attribute not found

**Meaning:**

This unfortunate error message is generated by the netcdf library so we have no opportunity to easily improve it. It actually means that there is an attribute missing from one of the variables in your initial conditions netcdf file.

The best thing is to change the verbose setting in your run.prm to 4 until you have resolved this problem. You will then get information about each attribute that is being loaded from your initial conditions netcdf file like the following:

readBMTracerInfo: reading long_name for S_seabirds_20_StructN

ncattget: ncid 65536: NetCDF: Attribute not found

This means the variable 'S_seabirds_20_StructN' is missing the 'long_name' attribute. Best to create a cdf version of your initial conditions nc file using ncdump, hand edit to add the attribute and then create an updated nc version of the files using ncgen. See [Atlantis Documentation](atlantis-documentation.qmd) for more information about ncdump/ncgen if you are unfamiliar with this workflow. 

---
