---
title: "MacroEcology Discussions"
author: "Fulton, Beth (Environment, Hobart)"
---

# Macroecology, macrophysiology and urban scaling laws

Here are a bunch of collected papers on macroecology and macrophysiology and urban scaling. You can access them by looking under the attachments page (under page operations on the side panel to the left of this page) or by clicking the links below.

###### Archive of papers:

I have included all the papers I have dragged together on this over the years, you will no doubt have more (or have these already), but just in case....

This archive is broken into 4 parts ([i](attachments/43157310.zip) , [ii](attachments/43157309.zip) , [iii](attachments/43157312.zip) , [iv](attachments/43157311.zip) ) so the individual zip files aren't too enormous.

###### Urban Scaling:

In an effort to see if the same kind of macroecology principles hold for human system properties I've been digging into urban scaling. I've included a range of [papers](attachments/43156805.zip) I've come across and a [talk by Geoff West](attachments/43156793.mp4) on it.
