---
title: "Run Input File"
author: "Fulton, Beth (Environment, Hobart)"
---

The run input file specifies general things like how long the model should run for and what sort of debugging output is required.

| Parameter Name | Description | Possible values |
| --- | --- | --- |
| verbose 0 | Turn on the verbose debug logging output. This will mostly be written to the log file but some will be written to standard out. | 0 = no additional debugging output, 1 = some debugging output, 2 = very verbose |
| flagecon_on | Flag showing whether want economics loaded and submodel | 0 = not run, 1 = run Note if you provide these input files in the command line these values are automatically set to TRUE |
| flag_fisheries_on | Flag showing whether want fisheries loaded and submodel | run (1) or not (0) |
| flag_skip_biol 0 | Flag showing whether want biological model run | (1) or not (0 - only used when debugging fisheries) |
| flag_skip_phys 0 | Flag showing whether want physics model run | (0) or not (1 - only used when debugging fisheries) |
| external_populations 0 | Flag indicating whether a age structured population dynamics model is used to track growth and mortality while an age-structured group is outside the model domain or not | (0) a simple growth and mortality correction is applied to migrators on their return to the system (1) full age structured population model is used |
| flag_sanity_check 1 | Flag indicating whether to check recruitment events and precent recruitment cascades (which may occur if the gestation or recruitment period is roughly the same length as the time between reproductive or spawning events). | 0=no, replicate old code  1=prevent cascades |
| flagenviro_warn  0 | Flag indicating that whether want earnings about environmental constraints on movement recorded to the logfile | 0 = no, 1 = yes |
| track_rugosity_arag 0 | Flag indicating that rugosity and aragonite saturation to be tracked - needed for corals | 0 unless want to do coral model (or some acidification models) |
| track_pH 0 | Flag indicating that want to track pH | 0 unless want to do acidification model |
| track_contaminants 0 | Flag indicating whether contaminants are being used in the model | 0 = no, 1 = yes |
| flag_contam_sanity_check 0 | Whether you need to check the contaminant fluxes (for the debugging or calibration of the contaminant model components) | 0 = no (off), 1 = yes (on) |
| flag_contamGrowthModel 0 | Flag indicating how to apply the impact of contaminant on growth | 0 = no effect, 1 = InVitro method (using a simple scalar), 2 = logistic effects model |
| flagpassivetracer 0 | Flag indicating whether a passive tracer is needed for tracking transports or not | 0 = no, 1 = yes |
| flag_pollutant_impacts 0 | Flag indicating whether to include noise and light pollution | 0 = no, 1 = yes |
| checkbox 80 | Give detailed logged output for this box | Set to greater then the number of boxes in your model if you don't want any detailed debugging on |
| checkstart 366666660 day | Start detailed logged output after this date | Set this to a very large number eg 366666660 day if you don't want debuggin on |
| checkstop 1900 day | Stop detailed logged output after this date |
| fishtest 0 | Count up total population for each vertebrate after each main subroutine: 0=no, 1=yes | This will be written to the log file. |
| flaggape 0 | Periodically list prey vs gape statistics (tuning diagnostic) | Should be 0 unless debugging - will generate output to the log file |
| flagchecksize 0 | Periodically list relative size (tuning diagnostic) | Also written to log file |
| flagagecheck 0 | Periodically list age structure per cohort (tuning diagnostic) |
| flagdietcheck 0 | Periodically list realised diet matchups (tuning diagnostic) |  |
| flag_age_output 1 | When doing output for whole model output biomass per age class per functional group |  |
| checkNH 0 | Give detailed logged output for NH in checkbox |  |
| checkDL 0 | Give detailed logged output for DL in checkbox |  |
| checkDR 0 | Give detailed logged output for DR in checkbox |  |
| checkbiom 0 | Give detailed logged output for biomasses in checkbox |  |
| which_fleet 33 | ID number of fleet to track (if don't want to track anything set to 33 (for other fleets see list below) |
| which_check 80 | ID number of group to track (if don't want to track anything set to 80 (for other groups see list below) |
| move_check 67 | ID number of group where tracking movements (if don't want to track anything set it to 67) |
| fishmove 1 | Set to 0 to turn vertebrate movement off for debugging purposes |
| debug 0 | Debugging options - this flag will turn on various debugging output options. All debugging statements are written to the log file | The current list of debug options can be found [here](43155514.qmd) |
| debug_it 0 | If set to 1 the it_count value will be printed to the log file at the end of each adaptive timestep. The it_count value is used to count the number of adaptive timesteps in each model timestep |
| title Dynamically Scen4 fished AMS model 2000 | The model title - this is written out to the output netcdf file |
| dt 12 hour | The model timestep. This just depends on the model | eg 12 hour time step |
| tstop 1900 day | Stop time after the given period (7320) | eg 10 years = 365 * 10 |
| toutstart 0 day | Output start time | start writing output to the output netcdf file after this day. |
| toutinc 90 day | Write output with this periodicity - write out data to the output netcdf file with this frequency - the greater the frequency the bigger the file |
| toutfinc 90 day | Write fisheries output with this periodicity - write data to the fishery netcdf file with this frequency |
| tsumout 90 day | Write stock state summary with this periodicity - print out data to the biomIndex.txt output file |
| flagannual_Mest 0 | Whether to write out estimates of mortality per predator annually (1) or not (0) |
| fishout 1 | Switch to turn fisheries output. | on = 1, off = 0 |
| flagreusefile 2 | Switch to show want to append output file. | no = 0, yes = 1, replace = 2 |
| **Parameters defining the numbers of certain types of groups (needed to parameter arrays in the initialisation section of the model, best left untouched for now)** |
| K_num_tot_sp 67 | total number of biological groups in the model |  |
| K_num_vert_sp 35 | total number of vertebrate groups in the model |  |
| K_num_stocks_per_sp 4 | maximum number of stocks per group in the model |  |
| K_num_cohorts 10 | maximum number of cohorts (age stages) for a vertebrate group |  |
| K_num_invert 24 | total number of invertebrate groups in the model |  |
| K_num_invcohorts 2 | maximum number of cohorts for an invertebrate group |  |
| K_num_invmig 9 | Maximum number of vertically migrating invertebrate groups |  |
| K_num_bed_types 3 | maximum number of seabed types (currently only reef, soft and flat) |  |
| K_num_cover_types 10 | maximum number of habitat types |  |
| K_num_detritus 6 | maximum number of detritus |  |
| **Parameters defining the numbers of certain types of fisheries (needed to parameter arrays in the initialisation section of the model, best left untouched for now)** |
| K_num_fisheries 33 | Maximum number of fisheries |  |
| K_num_subfleet 5 | Maximum number of sub fleets (vessel types) |  |
| K_num_fished_sp 47 | Maximum number of groups targeted by fishing |  |
| K_num_impacted_sp 51 | Maximum number of groups impacted by fishing (target or bycatch) |  |
| K_num_ports 17 | Maximum number of ports in the model area |  |
| K_max_num_zoning 1 | Maximum number of spatial zonings used in the model |  |
| K_num_reg 2 | Maximum number of management zonings used in the model |  |
| K_num_markets 2 | Maximum number of markets in the model area |  |
| K_num_catchqueue 7 | Length (in days) of list of catches used in running average to give recent CPUE for effort model 8 |  |
| K_num_basket 2 | Maxiumum number of species in basket quota |  |
| **Location parameters** |
| flaghemisphere 0 | Flag for hemisphere model is in. | (0 = southern; 1 = northern) |
| flagIsEstuary 0 | Flag to indicate if the model is estuary. If true a sediment tracer is required in the initial conditions input file. | Should be 0 for most people |
| flagIsPolar 0 | Flag indicating polar - so there will be 24 hrs of daylight/night seasonally | Should be 0 for most people |
| Parameters for rescaling initial vertebrate densities - only for use in emergencies, should really update the cdf file instead |
| flagscaleinit 1 | Flag to indicate whether scaling initial densities (for vertebrate/age structured groups) and biomass pools. | (1=yes, 0=no) |
| Multiplicative scalar for initial numbers (for age structured groups) and biomasses (as read-in from cdf file). Works for age structured groups and biomass pools but not detritus. It must have 1 entry per group in the groups.csv file | init_scalar 35  0.25 1 0.75 1 0.67 1 1 0.8 1 1 1 1 1 1 0.3 1 1 1 1 0.28 1 0.5 0.8 0.2 1 0.3 1.2 1 0.7 1 0.135 1 1 1 1 |
