---
title: "Solar Radiation"
author: "Gorton, Bec (Environment, Hobart)"
---

The solar radiation data can be provided in two possible formats:

### Time Series file (.ts)

This is the traditional method that has been used in past models. This format allows the modeller to provide a single value for the entire model for a given timestamp.

Sample forcing file parameters:

Solar_radiation inputs/GladstoneSolar.ts  
Solar_radiation_rewind 1

Data Format:

```
## COLUMNS 2

##
## COLUMN1.name Time

## COLUMN1.long_name Time
## COLUMN1.units days since 1990-01-01 00:00:00 +10

## COLUMN1.missing_value -999.000000
##
## COLUMN2.name swr

## COLUMN2.long_name Short wave radiation
## COLUMN2.units W m-2

## COLUMN2.missing_value -999.000000
##
366 201.6875
367 167.458328
368 106.75
369 175.104172
......
```

### NetCDF File (.nc)

This is new functionality in the Atlantis trunk code from 10th September 2015. This format allows modellers to provide a value per box.

Sample forcing file parameters:

Solar_radiation inputs/Gladstone305_6HourSWR.nc  
Solar_radiation_rewind 1

The Atlantis code will check to see if the Solar_radiation file name ends with ts or nc to work out what type of file is provided. 

Data Format:

```
netcdf Gladstone305_6HourSWR {
dimensions:
	t = UNLIMITED ; // (120 currently)
	b = 305 ;
variables:
	double t(t) ;
		t:units = "seconds since 2010-01-01 00:00:00 +10" ;
		t:dt = 21600. ;
	double swr(t, b) ;
		swr:_FillValue = 0. ;
// global attributes:
		:title = "swr data for Gladstone Atlantis model." ;
		:geometry = "GHHP_xy_0p0001_July.bgm" ;
		:parameters = "" ;
}
```
