---
title: "TasCERF Atlantis Model"
author: "Gorton, Bec (Environment, Hobart)"
---

### Model Background

### BGM File Generation

The shapefiles for this model were generated by Mike Fuller and Reg Watson. These shapefiles are in geographical co-ordinates.   
The shapefiles are stored in the atlantis repository at:

<https://svnserv.csiro.au/svn/atlantis/GISData/TasCerf>

The depth values were added to the shapefile on the 2nd December 2009 by Bec Gorton. The depth values were from a spreadsheet from Reg Watson 19 Nov 2009.

The shapefiles that include valid botz value are in the Tas_CERF_20091202 folder.

The [BGMGenerator](bgmeditor.qmd) was then used to generate two bgm files for this model.

1. Geographical co-ord  
2. Tasmanian centered Lambert azimuthal equal area (<http://spatialreference.org/ref/sr-org/6766/>)

23rd December 2009

Mike Fuller and Mark Hepburn identified a sliver in the tasCERF bgm file. This was removed from the master shapefile and a new set of bgm files have been created. These are also stored in the <https://svnserv.csiro.au/svn/atlantis/GISData/TasCerf>  
location.

These files are now being used to create the hydro input files.

### Model Hydro File Generation

The files that are used by the HydroConstruct program are generated by a series of Matlab scripts written by Jeff Dunn. Due to other project demands these are now managed by Bec Gorton.

The hydro construct code expects averaged flow per face which is calculated by the [FaceFlow Matlab](/pages/createpage.action?spaceKey=Atlantis&title=FaceFlow+Matlab&linkCreation=true&fromPageId=43155701) code.

The FaceFlow Matlab code used to generate the face flow data for the tasCERF model is in
<https://svnserv.csiro.au/svn/atlantis/Matlab/hydro/trunk/TasCERF>

The main script is called createHydro.m

BlueLink data:  
The hydro files for the TasCERF model are based on BlueLink data. The contact for this Bluelink data is Dr David Griffin at CMAR.

The bluelink data has been mapped to:

sudo mount nfstas01-hba:/not-backed-up/5/bluelink-interim /home/blueNew

The Faceflow matlab code needed a few changes to allow for the new model and the Bluelink model now generates monthly horizontal flux files instead of daily so the code needed to be changed to allow for this.

#### Hydro Progress Notes

##### 16th Feb 2010

A 1 year version of the files are being generated. These are currently being run through the faceFlow code. Once is is done they will be run through HydroConstruct to pick out any problem boxes. Due to the simple structure of this model i wouldn't expect there to be many problems - perhaps some discrepancy in bathymetry resulting in some layers where there is no flux.
