---
title: "Invertebrate size calculations for use in size based selectivity"
date: "2016-06-02"
author: "Gorton, Bec (Environment, Hobart)"
---

Previously the size of inverts was assumed to be 1.0 when calculating selectivity. The updated code reads in two new values from the biology.prm file.

li_a_invert 0.01
  
li_b_invert 3.0

These values are used for all inverts much the same way the li_a and li_b values are set for all vertebrates.

For invertebrates the code is now:

if (FunctGroupArray[guildcase].sn[chrt] > 0) {
  
Wgt = X_RS * FunctGroupArray[guildcase].sn[chrt];
  
li_a = bm->li_a_invert;
  
li_b = bm->li_b_invert;

wi = (Wgt * k_wetdry * bm->X_CN) / 1000.0;
  
w_on_a = wi / (li_a + small_num);
  
li = pow(w_on_a, li_b);
  
}else{
  
li = 1.0;
  
}

This change has been checked in as revision 6022 in the bec_dev branch and 6023 in the trunk code.

These changes may change the output of your model if you are using selectivity in the harvest code. It depends on the parameters you are using. Contact Bec for help to check things are not changing if required.


---

[← Back to Changelog](../changelog.qmd)
