---
title: "Previous changes made to input files"
date: "2012-07-05"
author: "Gorton, Bec (Environment, Hobart)"
---

Moved the changes to input files into a news format.

|  |  |  |
| --- | --- | --- |
| Sep-2008 | Added the following to the biology input file:   C_PB_T15 0.0 Clearance rate of pelagic bact mg3(mg N)-1d-1 0.0002 - 0.004   C_BB_T15 0.0 Clearance rate of sed bact mg3(mg N)-1d-1 0.0002 - 0.004 | Generalising the biology input file parsing |
| 30-sep-2008 | flagcullPIN becomes flagfishPIN in harvest input file | Need to generalise the fisheries input file parsing |
| 01-Oct-2008 | Fisheries. Added   flagfishBD 0 1=fishing of deposit feeders, 0=off 0   flagfishMA 0 1=fishing of macroalgae, 0=off 0     also   flag_access_thru_wc_BD 0 1=can access deposit feeders through the water column, 0=no 0   flag_access_thru_wc_MA 0 1=can access macroalgae through the water column, 0=no 0 | Trying to generalise the fisheries input file parsing |
| 27 October 2008 | Added to biology input file:   invading_sp_model (set this to 1 for now as 0=no invader and more complex options of 2 or more don't work yet)   InvaderIndex (invading species guild index, which I guess you get from the list in the functionalgroup.csv)   minInvaderAge (minimum cohort entering as invading species - 0 for urchins as only have one cohort)   maxInvaderAge (maximum cohort entering as invading species - again I guess 0 is most appropriate here)   InvaderEntryBox (box ID for first box invading species arrives in)   InvaderMinDepth (minimum depth invading species tolerates)   InvaderMaxDepth (maximum depth invading species tolerates)   InvaderStartDay (day invading species enters the system)   InvaderEndDay (day invading species stops entering the system)   InvaderScalar (increase per year of invading species - so what to scale original biomass by to represent invading species entering)   InvaderSpeed (speed of spread of invading species) | Beth has added the following additional parameters to the biological input files to support invading species |
| 05-Nov-2008 | Changed the KUP, KLP and KDEP species parameters in the biology input file to functional group values instead of a mixture of functional groups and groups of functional groups like deepfish. Example change is the following:   KLP was:   KLP_fish 0.00001 Lower prey selection size limit for fish 0.005   KLP_deepfish 0.00001 Lower prey selection size limit for deepwater fish (FMN, FDO) 0.005   KLP_otherfish 0.00001 Lower prey selection size limit for other (FDD) fish 0.005   KLP_tuna 0.00001 Lower prey selection size limit for tuna (FVT and FVO) 0.005   KLP_shark 0.00001 Lower prey selection size limit for sharks 0.005   KLP_bird 0.00001 Lower prey selection size limit for seabirds 0.005   KLP_baleen 1.0e-10 Lower prey selection size limit for baleen whales 0.0001   KLP_whale 1.0e-8 Lower prey selection size limit for toothed whale 0.0001   KLP_mammal 0.000008 Lower prey selection size limit for mammals 0.0001   KLP_CEP 0.0001 Lower prey selection size limit for cephalopods 0.005   KLP_ZG 0.0001 Lower prey selection size limit for gelatinous zooplankton 0.001   KLP_BMS 0.0000001 Lower prey selection size limit for gelatinous zooplankton 0.001   and is now:   #Gape size for vertebrates, to determine available prey fish groups   KLP_FPS 0.00001   KLP_FPL 0.00001   KLP_FPO 0.00001   KLP_FVD 0.00001   KLP_FVV 0.00001   KLP_FVS 0.00001   KLP_FVT 0.00001   KLP_FVO 0.00001   KLP_FVB 0.00001   KLP_FMM 0.00001   KLP_FMN 0.00001   KLP_FBP 0.00001   KLP_FDD 0.00001   KLP_FDS 0.00001   KLP_FDB 0.00001   KLP_FDC 0.00001   KLP_FDO 0.00001   KLP_FDE 0.00001   KLP_FDF 0.00001   KLP_FDP 0.00001   KLP_FDM 0.00001   KLP_SHD 0.00001   KLP_SHC 0.00001   KLP_SHP 0.00001   KLP_SHB 0.00001   KLP_SHR 0.00001   KLP_SSK 0.00001   KLP_SB 0.00001   KLP_SP 0.00001   KLP_REP 0.00001   KLP_PIN 0.000008   KLP_WDG 0.000008   KLP_WHB 1.00E-10   KLP_WHT 1.00E-08   KLP_WHS 1.00E-08   KLP_PL 0   KLP_PS 0   KLP_DF 0   KLP_MA 0   KLP_MB 0   KLP_SG 0   KLP_ZG 0.0001   KLP_ZL 0   KLP_ZM 0   KLP_ZS 0   KLP_PB 0   KLP_BB 0   KLP_BO 0   KLP_BD 0   KLP_BC 0   KLP_BFS 0   KLP_BFD 0   KLP_BFF 0   KLP_BG 0   KLP_BMS 0.0000001   KLP_BMD 0.0000001   KLP_BML 0.0000001   KLP_CEP 0.0001   KLP_PWN 0.0000001   KUP was:   KUP_fish 0.42 Upper prey selection size limit for fish 0.2 - 0.4   KUP_deepfish 0.6 Upper prey selection size limit for deepwater fish (FDO) 0.2 - 0.6   KUP_otherfish 0.95 Upper prey selection size limit for other fish (FDD) 0.2 - 0.6   KUP_mesopelag 0.9 Upper prey selection size limit for mesopelagic fish (FMM, FMN) 0.2 - 0.6   KUP_shark 0.4 Upper prey selection size limit for sharks 0.2 - 0.4   KUP_bird 0.25 Upper prey selection size limit for seabirds (lower as fly off) 0.1 - 0.2   KUP_baleen 2.0e-6 Upper prey selection size limit for baleen whales 0.0001   KUP_whale 15.0 Upper prey selection size limit for toothed whales 0.2 - 15.0   KUP_mammal 0.4 Upper prey selection size limit for other mammals 0.2 - 0.4   KUP_CEP 0.4 Upper prey selection size limit for cephalopods 0.2 - 0.4   KUP_ZG 0.5 Upper prey selection size limit for gelatinous zooplankton 0.2 - 0.7   KUP_BMS 0.1 Upper prey selection size limit for gelatinous zooplankton 0.2 - 0.7   and is now:   KUP_FPS 0.42   KUP_FPL 0.42   KUP_FPO 0.42   KUP_FVD 0.42   KUP_FVV 0.42   KUP_FVS 0.42   KUP_FVT 0.42   KUP_FVO 0.42   KUP_FVB 0.42   KUP_FMM 0.9   KUP_FMN 0.9   KUP_FBP 0.42   KUP_FDD 0.95   KUP_FDS 0.42   KUP_FDB 0.42   KUP_FDC 0.42   KUP_FDO 0.6   KUP_FDE 0.42   KUP_FDF 0.42   KUP_FDP 0.42   KUP_FDM 0.42   KUP_SHD 0.4   KUP_SHC 0.4   KUP_SHP 0.4   KUP_SHB 0.4   KUP_SHR 0.4   KUP_SSK 0.4   KUP_SB 0.25   KUP_SP 0.42   KUP_REP 0.4   KUP_PIN 0.4   KUP_WDG 0.4   KUP_WHB 2.00E-06   KUP_WHT 15   KUP_WHS 15   KUP_PL 0   KUP_PS 0   KUP_DF 0   KUP_MA 0   KUP_MB 0   KUP_SG 0   KUP_ZG 0.5   KUP_ZL 0   KUP_ZM 0   KUP_ZS 0   KUP_PB 0   KUP_BB 0   KUP_BO 0   KUP_BD 0   KUP_BC 0   KUP_BFS 0   KUP_BFD 0   KUP_BFF 0   KUP_BG 0   KUP_BMS 0.1   KUP_BMD 0.1   KUP_BML 0.1   KUP_CEP 0.4   KUP_PWN 0.1   KDEP was:   #Depth consumers can dig "into," are found down to in the sediment   KDEP_BFS 0.003 Sediment penetration depth of shallow filter feeders m 0.003   KDEP_BFF 0.003 Sediment penetration depth of other filter feeders m 0.003   KDEP_BFD 0.003 Sediment penetration depth of deep filter feeders m 0.003   KDEP_BO 0.03 Sediment penetration depth of meiobenthos m 0.03   KDEP_BD 0.1 Sediment penetration depth of deposit feeder m 0.01 - 0.3   KDEP_BC 0.1 Sediment penetration depth of infaunal carniv m 0.01 - 0.3   KDEP_BG 0.005 Sediment penetration depth of benth grazers m 0.001 - 0.01   KDEP_BMS 0.001 Sediment penetration depth of shallow macrozoobenthos m 0.00001 - 0.002   KDEP_BMD 0.001 Sediment penetration depth of deep macrozoobenthos m 0.00001 - 0.002   KDEP_BML 0.001 Sediment penetration depth of megazoobenthos m 0.00001 - 0.002   KDEP_CEP 0.003 Sediment penetration depth of cephalopods m 0.003   KDEP_PWN 0.001 Sediment penetration depth of prawns m 0.00001 - 0.002   KDEP_Demfish 1.0 Sediment penetration depth of demersal fish m 0.00001 - 0.002   KDEP_Pelfish 1.0 Sediment penetration depth of pelagic fish m 0.00001 - 0.002   KDEP_SB 0.05 Sediment penetration depth of seabirds m 0.01 - 0.3   KDEP_SHD 0.08 Sediment penetration depth of demersal sharks m 0.001 - 0.01   KDEP_PIN 0.001 Sediment penetration depth of pinnipeds m 0.00001 - 0.002   and is now:   KDEP_FPS 1   KDEP_FPL 1   KDEP_FPO 1   KDEP_FVD 1   KDEP_FVV 1   KDEP_FVS 1   KDEP_FVT 1   KDEP_FVO 1   KDEP_FVB 1   KDEP_FMM 1   KDEP_FMN 1   KDEP_FBP 1   KDEP_FDD 1   KDEP_FDS 1   KDEP_FDB 1   KDEP_FDC 1   KDEP_FDO 1   KDEP_FDE 1   KDEP_FDF 1   KDEP_FDP 1   KDEP_FDM 1   KDEP_SHD 0.08   KDEP_SHC 0.08   KDEP_SHP 0.08   KDEP_SHB 0.08   KDEP_SHR 0.08   KDEP_SSK 0.08   KDEP_SB 0.05   KDEP_SP 0.001   KDEP_REP 0.08   KDEP_PIN 0.001   KDEP_WDG 0.001   KDEP_WHB 0.001   KDEP_WHT 0.001   KDEP_WHS 0.001   KDEP_PL 0   KDEP_PS 0   KDEP_DF 0   KDEP_MA 0   KDEP_MB 0   KDEP_SG 0   KDEP_ZG 0   KDEP_ZL 0   KDEP_ZM 0   KDEP_ZS 0   KDEP_PB 0   KDEP_BB 0   KDEP_BO 0.03   KDEP_BD 0.1   KDEP_BC 0.1   KDEP_BFS 0.003   KDEP_BFD 0.003   KDEP_BFF 0.003   KDEP_BG 0.005   KDEP_BMS 0.001   KDEP_BMD 0.001   KDEP_BML 0.001   KDEP_CEP 0.003   KDEP_PWN 0.001      Correction The KDEP_SP value should be the same as the value for fixh. ie 1. | This simplifies the Atlantis code and adds additional flexibility in the model input parameters |
| 18th November | Added the following to the run.prm file:   K_num_catchqueue 1       Added to the fisheries input file #Threshold CPUE above which invest in more effort kg d-1   midwcCEP_mEff_thresh_top 0.0   jigCEP_mEff_thresh_top 0.0   midwcFP_mEff_thresh_top 0.0   dredgeBFS_mEff_thresh_top 0.0   netFD_mEff_thresh_top 0.0   netSH_mEff_thresh_top 0.0   plineFVO_mEff_thresh_top 0.0   pseineFVO_mEff_thresh_top 0.0   pseineFP_mEff_thresh_top 0.0.   trapBMS_mEff_thresh_top 0.0   trapFD_mEff_thresh_top 0.0   dtrawlBMS_mEff_thresh_top 0.0   dtrawlCEP_mEff_thresh_top 0.0   dtrawlFD_mEff_thresh_top 0.0   dtrawlFDB_mEff_thresh_top 0.0   dtrawlFDO_mEff_thresh_top 0.0   midwcFD_mEff_thresh_top 0.0   dseineFDB_mEff_thresh_top 0.0   dlineFD_mEff_thresh_top 0.0   dlineFVS_mEff_thresh_top 0.0   dlineSH_mEff_thresh_top 0.0   diveBG_mEff_thresh_top 0.0   pseineFVS_mEff_thresh_top 0.0   cullPIN_mEff_thresh_top 0.0   REC_mEff_thresh_top 0.0   ptrawlPWN_mEff_thresh_top 0.0   dtrawlFBP_mEff_thresh_top 0.0   midwcZL_mEff_thresh_top 0.0   trapFDE_mEff_thresh_top 0.0   dlineFDE_mEff_thresh_top 0.0   netFDE_mEff_thresh_top 0.0   midwcPWN_mEff_thresh_top 0.0   mowMA_mEff_thresh_top 0.0   #Proportional increase/decrease in effort in effort if outside CPUE thresholds   #Effort decrease will be (1-mEff_prop) and increase will be (1+mEff_prop)   midwcCEP_mEff_shift 0.0   jigCEP_mEff_shift 0.0   midwcFP_mEff_shift 0.0   dredgeBFS_mEff_shift 0.0   netFD_mEff_shift 0.0   netSH_mEff_shift 0.0   plineFVO_mEff_shift 0.0   pseineFVO_mEff_shift 0.0   pseineFP_mEff_shift 0.0   trapBMS_mEff_shift 0.0   trapFD_mEff_shift 0.0   dtrawlBMS_mEff_shift 0.0   dtrawlCEP_mEff_shift 0.0   dtrawlFD_mEff_shift 0.0   dtrawlFDB_mEff_shift 0.0   dtrawlFDO_mEff_shift 0.0   midwcFD_mEff_shift 0.0   dseineFDB_mEff_shift 0.0   dlineFD_mEff_shift 0.0   dlineFVS_mEff_shift 0.0   dlineSH_mEff_shift 0.0   diveBG_mEff_shift 0.0   pseineFVS_mEff_shift 0.0   cullPIN_mEff_shift 0.0   REC_mEff_shift 0.0   ptrawlPWN_mEff_shift 0.0   dtrawlFBP_mEff_shift 0.0   midwcZL_mEff_shift 0.0   trapFDE_mEff_shift 0.0   dlineFDE_mEff_shift 0.0   netFDE_mEff_shift 0.0   midwcPWN_mEff_shift 0.0   mowMA_mEff_shift 0.0 | This allows for CPUE related effort model (simple increase/decrease based on whether CPUE outside defined band) |
| 6th December | Added to the run.prm   flagannual_Mest 1      # Write out mortality per predator annually (1) or not (0) | This identifies how often want mortality per predator indices |
| 8th December | Added to the harvest.prm   # This sets the start date of a fishery in days after the start of the run     midwcCEP_tStart  0   jigCEP_tStart    0   midwcFP_tStart   0   dredgeBFS_tStart 0   netFD_tStart     0   netSH_tStart     0   plineFVO_tStart  0   pseineFVO_tStart 0   pseineFP_tStart  0   trapBMS_tStart   0   trapFD_tStart    0   dtrawlBMS_tStart 0   dtrawlCEP_tStart 0   dtrawlFD_tStart  0   dtrawlFDB_tStart 0   dtrawlFDO_tStart 0   midwcFD_tStart   0   dseineFDB_tStart 0   dlineFD_tStart   0   dlineFVS_tStart  0   dlineSH_tStart   0   diveBG_tStart    0   pseineFVS_tStart 0   cullPIN_tStart   0   REC_tStart       0   ptrawlPWN_tStart 0   dtrawlFBP_tStart 0   midwcZL_tStart   0   trapFDE_tStart   0   dlineFDE_tStart  0   netFDE_tStart    0   midwcPWN_tStart  0   mowMA_tStart     0     # This sets the end date of a fishery in days after the start of the run     midwcCEP_tEnd  1000000000   jigCEP_tEnd    1000000000   midwcFP_tEnd   1000000000   dredgeBFS_tEnd 1000000000   netFD_tEnd     1000000000   netSH_tEnd     1000000000   plineFVO_tEnd  1000000000   pseineFVO_tEnd 1000000000   pseineFP_tEnd  1000000000   trapBMS_tEnd   1000000000   trapFD_tEnd    1000000000   dtrawlBMS_tEnd 1000000000   dtrawlCEP_tEnd 1000000000   dtrawlFD_tEnd  1000000000   dtrawlFDB_tEnd 1000000000   dtrawlFDO_tEnd 1000000000   midwcFD_tEnd   1000000000   dseineFDB_tEnd 1000000000   dlineFD_tEnd   1000000000   dlineFVS_tEnd  1000000000   dlineSH_tEnd   1000000000   diveBG_tEnd    1000000000   pseineFVS_tEnd 1000000000   cullPIN_tEnd   1000000000   REC_tEnd       1000000000   ptrawlPWN_tEnd 1000000000   dtrawlFBP_tEnd 1000000000   midwcZL_tEnd   1000000000   trapFDE_tEnd   1000000000   dlineFDE_tEnd  1000000000   netFDE_tEnd    1000000000   midwcPWN_tEnd  1000000000   mowMA_tEnd     1000000000 | This allows for fisheries to be started after model starts or stops before model end run |
| 20th Dec 2008 | min_channel_depth added to biol.prm | It is the minimum depth of estuarine channels (so in tidal movements can have groups move on/off flats with the tides) |
| 22 Dec 2008 | Added the following to the biology input file   flagDC           1           DC: 1 = on, 0 = off                                               1 |
| 05 Jan 2009 | Added the following to the run input file and removed it from the assess input file     K_num_detritus   6         # Total number of detritus groups in the model (labile and refractory; water column and sediments) | The bm->K_num_macrofauna is calculated based on this value in atParamIO.c. |
| 07 Apr 2009 | Added the following to the biology input file;     lim_sun_hours   0         # Variable daylength: 0=no (i.e. always 12 hours), 1=yes (changes with season and latitude)     add swr_scalar       0.45      # Proportion of shortwave radiation available to photosynthesis | If yes is chosen a projection (so lat-long can be related to x-y) is needed in the bgm file and the swr_scalar value must be included in the biol.prm file so that get correct surface irradiance calculated |


---

[← Back to Changelog](../changelog.qmd)
